security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }
                    seb: { password: geheim, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        
        LOGIN_FIREWALL_1: 
            pattern: ^/login$
            anonymous: ~
        LOGIN_FIREWALL_2: 
            pattern: ^/login/register$
            anonymous: ~    
        secured_area:
                  pattern:    ^/
                  form_login:
                          login_path:  login
                          check_path:  login_check
                          use_referer: true
                  logout:
                        path: /logout
                        target: /login
    access_control: